<?php

require_once dirname(__FILE__).'/../../src/PHPExcel/Wrapper.php';

/**
 * Test class for PHPExcel_Wrapper
 * Generated by PHPUnit on 2010-12-14 at 09:28:52.
 */
class PHPExcel_WrapperTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var PHPExcel_Wrapper
   */
  protected $object;

  protected $testfile;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new PHPExcel_Wrapper;
    $this->testfile = dirname(__FILE__).'/../_files/simple.xls';
    $this->testfile2 = dirname(__FILE__).'/../_files/complex.xls';
  }
  
  public function testLoad()
  {
    $this->setExpectedException('Exception');
    $this->object->load('non existant file');
  }

  public function testGetPHPExcel()
  {
    $this->object->load($this->testfile);

    $this->assertType('PHPExcel', $this->object->getPHPExcel(), 'Type correct');
  }

  public function testConvertToSimpleArray()
  {
    $array = $this->object->load($this->testfile)->convertToSimpleArray();
    
    $this->assertEquals(5, count($array));
    $this->assertEquals(7, $array[2]['A']);
    $this->assertEquals(6, $array[1]['C']);

    $array = $this->object->load($this->testfile)->convertToSimpleArray('test_sheet');
    $this->assertEquals(2, count($array));
    $this->assertEquals("foo", $array[1]['col1']);
    $this->assertEquals(26, $array[0]['col2']);
  }

  public function testConvertToComplexArray()
  {
    $array = $this->object->load($this->testfile2)->convertToComplexArray();
  }
}
