language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"

install: composer update --prefer-source $COMPOSER_FLAGS
